sonar.organization=stefanheinecke
sonar.projectKey=matheapp
sonar.projectName=MathQuiz (matheapp)
sonar.sourceEncoding=UTF-8

sonar.sources=server,mobile
sonar.exclusions=**/node_modules/**,server/public/images/**,mobile/www/**,mobile/ios-plugin-source/**,**/*.pdf
sonar.tests=server/test
sonar.javascript.lcov.reportPaths=coverage/lcov.info
