sonar.projectKey=matheapp
sonar.projectName=MathQuiz (matheapp)
sonar.sourceEncoding=UTF-8

sonar.sources=server,mobile
sonar.exclusions=**/node_modules/**,server/public/images/**,mobile/www/**,mobile/ios-plugin-source/**,**/*.pdf
