sonar.organization=stefanheinecke
sonar.projectKey=stefanheinecke_mathapp
sonar.projectName=MathQuiz (matheapp)
sonar.sourceEncoding=UTF-8

sonar.sources=server,mobile
sonar.exclusions=**/node_modules/**,server/public/images/**,mobile/www/**,mobile/ios-plugin-source/**,**/*.pdf,server/test/**
sonar.tests=server/test
sonar.javascript.lcov.reportPaths=coverage/lcov.info
